spring:
  application:
    name: jooq
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8024
logging:
  level:
    Exposed: DEBUG